language: node_js

node_js:
  - 8

before_install:
  - npm i -g npm@latest

install:
  - npm install

cache:
  directories:
    - "node_modules"

branches:
  except:
    - staging

sudo: false

script:
  - npm run lint

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: npm
    email: software@pod-point.com
    skip_cleanup: true
    api_key:
      secure: Qz+qEnaNkYG5uDXilWUt/zuuSQKKTIYDfsnZvS3XMzMWl7dtS9mOltuge93xwfjfghp7k0akaAumS8TskwaPyZ4+AWH11OYoia/AgjC7GKKcQ7DChvQ8dU5GzvznhZ0OpEBH+LS/Kl9bRMCXpIH665drlhibdo+lpLLTTNiqE9HclABqfrbkEjDal6YKmgRf+F/ddDLLf0Dn0eiSypqYU8UHBABkiX59i+bX+ewyvbRnaSpEauA+PLhCpVoltL5CvcxS2Gp43IZHgrRgwjiEszfHeLXs52LHqXe/GNTPd7H6dFiWvo6XuFxiHlUza1SjoOROSfaP131RNYAk3TxMic9OtJf6xgm7k2YN4KXFGqyMFMMz5SFRfmXHIQbDfpPu2ObE189SPyuIm+ZJUwof5ATrLjKooEukEOTsHwkEjcnH1UjCVymaNQhFUG42dh4oymCnzU5izbEMSCTlGQpLe6xTf7KbDwyhLXp6hks6ny1zLAAuBHncbm1kzk3lHq1KcG6WKVe9hfajeB2+wGwGQbVJVJ7gkMbQGWAEbn/O5GCbZAw8lbSVZL73TZqQ2Gc9HgiWKxZ6zmSZjkVUSJKbE1HtIcqjHxS6B4hDU4xobV8wkte4xSwSO19mV5qa4rSNc5NKsWd2vKeBrFmqxEfY13B8rjF43b07QmhLh1lHpR0=
    on:
      tags: true
      repo: Pod-Point/react-dom-components
