language: node_js

node_js:
  - 8

before_install:
  - npm i -g npm@latest

install:
  - yarn

cache:
  directories:
    - "node_modules"

branches:
  except:
    - staging

sudo: false

script:
  - npm run lint
  - npm run coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
